#!/bin/sh

# shellcheck shell=bash

_dockerfreeze() {
    # FIXME: Are cmds used?
    # shellcheck disable=SC2034
    local cur prev opts cmds
    # used by complete
    # shellcheck disable=SC2034
    COMREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    # used by complete
    # shellcheck disable=SC2034
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="-g -h -v -o --version --help --gitpod --output"
    if [[ ${cur} == -* ]] ; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
        return 0
    elif [[ ${cur} == r* ]]; then
        COMPREPLY=( $(compgen -W "$opts" "$cur") )
        return 0
    fi
}
complete -F _dockerfreeze dockerfreeze
