name: Bash

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: 
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
    - '**.bash'
    - "tools/dockerfreeze"

jobs:
  # Linting
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: debian:latest
      - name: Installing dependencies..
        run: if ! apt list --installed 2>/dev/null | grep -q ".*shellcheck.*"; then apt install -y shellcheck; fi
      - name: Linting..
        run: |
          cd "$GITHUB_WORKSPACE"

          # Process files
          ## NOTICE: Do not use for loop to avoid pitfall https://mywiki.wooledge.org/BashPitfalls#pf1
          git ls-files -z -- '*.bash' tools/dockerfreeze | while IFS= read -rd '' file; do
              printf 'linting bash file %s' "$file"
              shellcheck --external-sources --shell=bash "$file"
          done