name: Bash

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: 
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
    - '**.bash'
    - "tools/dockerfreeze"

jobs:
  # Linting
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies..
        run: if ! apt list --installed 2>/dev/null | grep -q ".*shellcheck.*"; then apt install -y shellcheck; fi
      - name: Linting..
        run: |
          cd "$GITHUB_WORKSPACE" # Change dir in required workspace
          # Process files
          ## NOTICE: Do not use for loop to avoid pitfall https://mywiki.wooledge.org/BashPitfalls#pf1
          while IFS= read -r -d '' file; do
            # Logic for bash completion file
            if [ "$file" = tools/dockerfreeze ]; then
              case "$(head -n1 "$file")" in
                "\#!/bin/false")
                  printf 'linting bash file %s' "$file"
                  shellcheck --external-sources --shell=bash "$file"
              esac
            elif [ "$file" != tools/dockerfreeze ]; then
              printf 'linting bash file %s' "$file"
              shellcheck --external-sources --shell=bash "$file"
            else
              printf 'UNEXPECTED: %s\n' "Unexpected happend while processing file '$file'"
              exit 255
            fi
          done